### ISSUE TITLE
Better OSX support

### ISSUE THREAD

**Issue by gdb** [ppaquette/doom-py#2]
In order to build this on OSX, I had to do the following (because I'm using brew's python):

```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON  -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7
```

As well as:

```
rm bin/vizdoom && ln -s vizdoom.app/Contents/MacOS/vizdoom bin/vizdoom
```

(Both come from the README: https://github.com/Marqt/ViZDoom.)

I'm not sure what the best way is to make the Python package do these automatically where appropriate — any thoughts?

**Comment by ppaquette** [comment]
Could you detect when OSX is used and call a different subprocess in setup.py (for python setup.py build)?

subprocess.check_call("cd doom_py; cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON -DBUILD_JAVA=OFF && make && rm -f vizdoom.so && ln -s bin/python/vizdoom.so vizdoom.so", shell=True)

**Comment by gdb** [comment]
Yeah, that's not too hard actually.

I was a bit worried that finding the right include path might be hard, but http://stackoverflow.com/questions/14375222/find-python-header-path-from-within-python indicates you can do `sysconfig.get_python_inc()`. I'm not sure about finding the PYTHON_LIBRARY value yet, but I'll play with it.

**Comment by gdb** [comment]
(BTW, is it ok if I make this into an official openai package, and upload to Pypi?)

**Comment by ppaquette** [comment]
Yes. That's why I didn't publish it.

It belongs as an official OpenAI package.

**Comment by gdb** [comment]
Cool, figured but just wanted to make sure. Thanks!
